import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { EdgeStoreProvider } from '@/lib/edgestore';
import { Toaster } from '@/components/ui/sonner';
import { ModalProvider } from '@/components/providers/modal-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Schubert',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <EdgeStoreProvider>
          <ModalProvider />
          <Toaster position="top-center" />
          {children}
        </EdgeStoreProvider>
      </body>
    </html>
  );
}
